In [51]:
data_file = 'data/ukwac-10L.txt'

In [52]:
join_me = ['to be', 'have a look']
import re
import random
write_file = data_file + '.cexp'
threshold = 0.5
with open(data_file, errors='ignore') as d, open(write_file, 'w') as w:
    jstats = {x : 0 for x in join_me}
    by_space = re.compile('\s+')
    for line in d:
        line = line.strip()
        if line:
            line = ' '.join(by_space.split(line))
            for j in join_me:
                js = line.count(j)
                if js:
                    jstats[j] += 1
                r = random.random()
                if r > threshold:
                    line = line.replace(j, '_'.join(j.split(' ')))
            w.write(line + '\n')
        
                    

In [53]:
jstats

{'to be': 38205, 'have a look': 171}

In [21]:
import random

In [24]:
random.random()

0.9458584969210958

In [54]:
import numpy

In [55]:
from pymagnitude import *

In [56]:
mag_file = '../tools/GloVe/cexp/ukwac-10L.cexp.magnitude'
vectors = Magnitude(mag_file)

In [57]:
from scipy.spatial.distance import cosine

In [83]:
def compose(comps, min_threshold=-0.15):
    #min_threshold = -0.15
    vcomps = []
    c_index = None
    for i, c in enumerate(comps):
        vc = v(c)
        if i == 0:
            c_index = vc < min_threshold
        else:
            c_index = c_index | (vc < min_threshold)
        vcomps.append(vc)
        
    vm = sum(vcomps)
    vm[c_index] = 0
    return vm
    

In [84]:
compose(['to', 'be'])

array([-0.0591901 ,  0.07170039, -0.1522574 , -0.0187132 ,  0.        ,
       -0.0586638 ,  0.        ,  0.10726529,  0.29655433, -0.16184181,
        0.1368624 ,  0.3018956 ,  0.2618757 ,  0.        , -0.0741246 ,
       -0.0711639 ,  0.0013055 ,  0.0326542 ,  0.        , -0.0418454 ,
        0.0542514 , -0.14339429, -0.018047  ,  0.0185707 , -0.1354312 ,
        0.1902972 , -0.16498241, -0.0811795 ,  0.10383499, -0.14371079,
       -0.1567065 ,  0.        ,  0.1818994 , -0.1314704 ,  0.191599  ,
        0.3127665 ,  0.028083  , -0.0904288 , -0.1292921 , -0.1478785 ,
        0.1578084 , -0.1192655 , -0.0746791 ,  0.1751726 ,  0.0727623 ,
        0.1378729 ,  0.2141796 , -0.2032266 ,  0.3170976 ,  0.0758035 ,
        0.0520217 ,  0.0532261 ,  0.0521596 , -0.1589828 , -0.056439  ,
       -0.0848725 , -0.0896006 ,  0.        ,  0.        ,  0.12442951,
       -0.0516488 , -0.1590414 ,  0.0610341 , -0.1051727 ,  0.        ,
       -0.0516866 ,  0.183944  , -0.20830199,  0.0514364 , -0.09

In [85]:
cosine(vectors.query('a'), vectors.query('a'))

0.0

In [86]:
v = lambda x : vectors.query(x)

In [87]:
jvs = [vectors.query(j) for j in join_me]

In [97]:
import numpy
for i,j in enumerate(join_me):
    jparts = j.split(' ')
    print(jparts)
    jpart_vs = [vectors.query(x) for x in jparts]
    #jpart_mean = sum(jpart_vs)
    jpart_mean = compose(jparts, min_threshold=-0.2)
    print(j, cosine(jpart_mean, v(j)))

['to', 'be']
to be 0.8518580178912096
['have', 'a', 'look']
have a look 0.26099742998378694


In [40]:
cosine(v('to') + v('be'), v('to_be'))

0.1532384157180786

In [46]:
sum([v('to'), v('be')])

array([-0.0591901 ,  0.07170039, -0.1522574 , -0.0187132 , -0.3855369 ,
       -0.0586638 , -0.2690843 ,  0.10726529,  0.29655433, -0.16184181,
        0.1368624 ,  0.3018956 ,  0.2618757 , -0.3131643 , -0.0741246 ,
       -0.0711639 ,  0.0013055 ,  0.0326542 , -0.51192224, -0.0418454 ,
        0.0542514 , -0.14339429, -0.018047  ,  0.0185707 , -0.1354312 ,
        0.1902972 , -0.16498241, -0.0811795 ,  0.10383499, -0.14371079,
       -0.1567065 , -0.4424857 ,  0.1818994 , -0.1314704 ,  0.191599  ,
        0.3127665 ,  0.028083  , -0.0904288 , -0.1292921 , -0.1478785 ,
        0.1578084 , -0.1192655 , -0.0746791 ,  0.1751726 ,  0.0727623 ,
        0.1378729 ,  0.2141796 , -0.2032266 ,  0.3170976 ,  0.0758035 ,
        0.0520217 ,  0.0532261 ,  0.0521596 , -0.1589828 , -0.056439  ,
       -0.0848725 , -0.0896006 , -0.3015425 , -0.2693216 ,  0.12442951,
       -0.0516488 , -0.1590414 ,  0.0610341 , -0.1051727 , -0.2383861 ,
       -0.0516866 ,  0.183944  , -0.20830199,  0.0514364 , -0.09

In [47]:
v('to') + v('be')

array([-0.0591901 ,  0.07170039, -0.1522574 , -0.0187132 , -0.3855369 ,
       -0.0586638 , -0.2690843 ,  0.10726529,  0.29655433, -0.16184181,
        0.1368624 ,  0.3018956 ,  0.2618757 , -0.3131643 , -0.0741246 ,
       -0.0711639 ,  0.0013055 ,  0.0326542 , -0.51192224, -0.0418454 ,
        0.0542514 , -0.14339429, -0.018047  ,  0.0185707 , -0.1354312 ,
        0.1902972 , -0.16498241, -0.0811795 ,  0.10383499, -0.14371079,
       -0.1567065 , -0.4424857 ,  0.1818994 , -0.1314704 ,  0.191599  ,
        0.3127665 ,  0.028083  , -0.0904288 , -0.1292921 , -0.1478785 ,
        0.1578084 , -0.1192655 , -0.0746791 ,  0.1751726 ,  0.0727623 ,
        0.1378729 ,  0.2141796 , -0.2032266 ,  0.3170976 ,  0.0758035 ,
        0.0520217 ,  0.0532261 ,  0.0521596 , -0.1589828 , -0.056439  ,
       -0.0848725 , -0.0896006 , -0.3015425 , -0.2693216 ,  0.12442951,
       -0.0516488 , -0.1590414 ,  0.0610341 , -0.1051727 , -0.2383861 ,
       -0.0516866 ,  0.183944  , -0.20830199,  0.0514364 , -0.09

In [104]:
vmmap = vectors.get_vectors_mmap()

In [120]:
from sklearn.cluster import KMeans, OPTICS, DBSCAN

In [ ]:
#vkmeans = KMeans(n_clusters = 20, random_state=0).fit(vmmap)
vkmeans = DBSCAN(min_samples=5).fit(vmmap)

In [114]:
from collections import Counter
cassigns = [[] for i in range(20)]

for i, cassign in enumerate(vkmeans.labels_):
    cassigns[cassign].append(vectors.index(i)[0])


In [116]:
for i, cassign in enumerate(cassigns):
    print(i, len(cassign), cassign[:20])

0 35677 ['Tir', 'feng', 'mis', 'MOBUTU', 'ELSE', 'Gofal', 'Lei', 'Surnames', 'Ein', 'SILVER', 'biloba', 'mit', '*No', '5M', 'ANNOUNCES', 'Begum', 'Kahlo', 'Massimo', '****Hotel', '10.74']
1 23640 ['July', 'September', 'April', 'March', 'October', 'January', 'August', 'November', '14', 'December', 'February', '13', '17', 'OF', '21', '19', 'PM', 'Monday', '22', '23']
2 20108 ['ext', '023', 'OVER', 'Approx', 'BEFORE', 'WERE', 'SOME', 'THEIR', 'Chem', 'Biol', 'ANSWER', 'SINGLE', 'Exp', 'Enlisted', 'Ironbridge', 'Acta', 'THEM', 'fr', 'Cf', 'KEEP']
3 32436 ['WITH', '_________________', 'HEALTH', 'WORLD', 'SERVICE', 'SPECIAL', 'LIST', 'DEVELOPMENT', 'GET', 'ISSN', 'SUPPORT', 'GOOD', 'INTO', 'l.', 'MANAGEMENT', 'NEED', 'OFFICE', 'ONLINE', 'SCHOOL', 'UNIVERSITY']
4 34490 ['val', 'blah', 'peer-reviewed', 're-appointed', '2px', '3px', 'WG3', 'positional', 'ccp4bb', 'OWN', 'today.', '373', 'ADDRESS', 'Cassette', 'CASCAiD', 'non-cash', 'HPV', 'sites.', '499.00', 'resources.']
5 50418 ['atmosphere',